### ISSUE TITLE
Complement function for "pick"

### ISSUE THREAD

**Issue by ctzurcanu** [scijs/ndarray#15]
this may be #9 put in other words
or in other words: a way to compose a ndarray by "glueing" slices

**Comment by rreusser** [comment]
@ctzurcanu: late on the issue too, but I added a couple functions to do this. They just use ndarray-ops anyway but handle the thinking for you. Allows either allocation or into a destination array.

See:
[ndarray-concat-cols](https://github.com/scijs/ndarray-concat-cols)
[ndarray-concat-rows](https://github.com/scijs/ndarray-concat-rows)
[scijs-ndarray-for-matlab-users](https://github.com/scijs/scijs-ndarray-for-matlab-users)
