### ISSUE TITLE
Remove Buffer dependency

### ISSUE THREAD

**Issue by mikolalysenko** [scijs/ndarray#17]
Browserify automatically inserts the buffer polyfill if any instance of Buffer is used.  We can avoid this by switching out the references to Buffer in this module, but we need a light weight method to detect if an object is a Buffer.

**Comment by hughsk** [comment]
https://github.com/feross/is-buffer :grin:

**Comment by mikolalysenko** [comment]
Thanks!  Fixed in ndarray@1.0.17
