### ISSUE TITLE
Consider adding ndarray to jsDelivr

### ISSUE THREAD

**Issue by neothemachine** [scijs/ndarray#19]
I'd like to include ndarray in a website as a simple script, without browserify or anything, and I don't want to distribute it myself, so I was looking for it at some CDNs but couldn't find it. I think it would be nice if it's added to https://www.jsdelivr.com

**Comment by rreusser** [comment]
Does this work for you?

https://wzrd.in/standalone/ndarray@latest

**Comment by neothemachine** [comment]
I actually moved over to using JSPM for dependency management which supports using npm packages out-of-the-box. So I cannot test your link easily right now. Why not create a simple demo page which uses that? This could demonstrate how easy it is to use it.

**Comment by rreusser** [comment]
ndarray by itself might be an exception, but it doesn't seem any non-browserify-aware cdn would play well with the ecosystem model since importing multiple browserified modules will result in tons of duplicate code.

In the console at jspm.io, this:

```javascript
System.import('npm:ndarray').then(function(ndarray) {
  x = ndarray(new Float32Array([1,2,3]),[3])
})
```

seems to work fine. It sounds like it applies a browserify-like strategy for de-duping similar dependencies (except is it runtime resolution?)

I'm working hard to find the time to be a responsible maintainer, so if you work with this and have luck, would it be possible for you to submit a README PR with 5-10 sample lines of code that explain how to work with this?

**Comment by neothemachine** [comment]
You're right about the duplication. Since I believe the ES6 module system is the future anyway, promoting JSPM (which supports that) may be a good idea.

With JSPM you can do runtime-resolution but also create self-contained bundles. For the README as a quick demo, the runtime resolution is probably the way to go. I'll see if I can write a minimal demo page, basically `<script src="https://jspm.io/system@0.16.js"></script>` and then some sample code like yours above.

**Comment by rreusser** [comment]
Thanks! And thanks for the suggestion on how to move this stuff toward the future!

**Comment by neothemachine** [comment]
```html
<!DOCTYPE html>
<html>
<script src="https://jspm.io/system@0.16.js"></script>
<script>
System.import('npm:ndarray').then(function(ndarray) {
  var mat = ndarray(new Float64Array([1, 0, 0, 1]), [2,2])
  console.log(mat)
})
</script>
</html>
```
That already works and should be enough for the readme code. But as that's quite lame, I'll now try to directly draw onto the pixels of a canvas. I find this interesting because a canvas pixel array (`canvas.getContext('2d').getImageData(0, 0, width, height).data`) is a 1-dim Uint8ClampedArray which actually represents a [height,width,4]-shape array (RGBA), and so by using ndarray we get the proper shape to work on it easily without doing annoying index acrobatics.

**Comment by rreusser** [comment]
Actually, that's great as-is! Would be great to throw single, full example html file into `examples/`, but probably best to keep the README example minimal. As a suggestion though, I'm particularly interested in the syntax for importing multiple modules. Like to fill an array, would it be (total guess):

```
System.import('npm:ndarray', 'npm:ndarray-fill').then(function(ndarray,fill) {
  var mat = ndarray(new Float64Array([1, 0, 0, 1]), [2,2])
  fill(mat,function(i) { return i; });
  console.log(mat)
})
```

**Comment by neothemachine** [comment]
Seems this is [not supported](https://github.com/systemjs/systemjs/issues/383) with such syntax. The workaround is nesting:
```js
System.import('npm:ndarray').then(function(ndarray) {
  System.import('npm:ndarray-fill').then(function(fill) {
    var mat = ndarray(new Float64Array([1, 0, 0, 1]), [2,2])
    fill(mat,function(i) { return i; });
    console.log(mat)
  })
})
```

**Comment by rreusser** [comment]
There's probably a nice compressed way to use `Array.prototype.reduce`, but what about:

```javascript
var mods = {}

Promise.all(['ndarray','ndarray-fill'].map((dep) => {
  return System.import('npm:'+dep).then((mod) => { mods[dep] = mod })
})).then(function() {
  window.ndarray = mods['ndarray']
  window.fill = mods['ndarray-fill']
})
```

**Comment by neothemachine** [comment]
`Promise` is not supported on IE yet, and some syntax you use (lambdas) is ES6 which you would still have to transpile. Also, I don't like the pollution of the global variable space. This is one of the main things the module system tries to prevent. I will think about it!

**Comment by rreusser** [comment]
The lambdas can go and sure, it's up to the user how to reference the resulting modules, and wouldn't jspm have to polyfill promises in order to provide the `.then` syntax in the first place? I guess then it'd be:

```javascript
var mods = {}
Promise.all(['ndarray','ndarray-fill'].map(function(dep) {
  return System.import('npm:'+dep).then(function(mod) { mods[dep] = mod })
})).then(function() {
  ...
})
```

If jspm/System doesn't provide it, I don't really see a simpler alternative than bootstrapping the process with a promise polyfill or just transpiling in the first place since your code will get infinitely nested as you ad modules otherwise.

**Comment by rreusser** [comment]
(Or you can do the thing with the counter and a check on each load to see if they're all loaded and a callback otherwise, but I'd prefer just to transpile or polyfill)

**Comment by neothemachine** [comment]
So, I found [this](http://stackoverflow.com/a/22582151), and the last sentence is relevant ("The better alternative really is to only have one entry point for an application, app.js and then have that load dependencies."), as this is how you develop applications bigger than toy examples anyway. In my own code I have a single call to
```html
    <script>
    	System.import('app/main')
    </script>
```
and in main.js there is ES6 code with import statements etc and no more `System.import`.

**Comment by rreusser** [comment]
Ah, I see. Makes sense. I conclude that I'd be better off spending my time just reading the docs instead of constructing ill-informed workarounds. :smile:

**Comment by neothemachine** [comment]
OK here it comes, hold on to something: https://rawgit.com/neothemachine/57a256e366b06773c40a/raw/2bf66071252c0a06fd40e274efe5bd970eeac5f9/ndarray.html

**Comment by neothemachine** [comment]
Let's close this for now since I personally don't need a bundled version anymore. The example / ES6 stuff could be put into a different issue.
