### ISSUE TITLE
ndarray reshape?

### ISSUE THREAD

**Issue by jbroll** [scijs/ndarray#2]
Is there a simple way to reshape an array?

Thanks,

John

**Comment by neothemachine** [comment]
What's the problem with reallocation? My use case is to access all elements of an ndarray irrespective of its shape, and I don't know how to do that (array is a subset) as there is also no flatten/ravel function.

**Comment by enobufs** [comment]
@mikolalysenkosuch a thing would require reallocating the underlying array

**Comment by enobufs** [comment]
I was looking for reshape() operation for ndarray, then came across this old issue...
> such a thing would require reallocating the underlying array

The in-place `reshape` I wish to have, is like the one by numpy, would not change the underlying array. Why would it require reallocation of underlying array??
