### ISSUE TITLE
Provide searchable API docs

### ISSUE THREAD

**Issue by neothemachine** [scijs/ndarray#21]
With the mass of ndarray extensions it's hard to find the functions you need. I would be happy about some simple document (can be in the wiki or just a Markdown file somewhere) which lists all functions from all extensions so that I immediately know what exists and where to find it.

**Comment by hughsk** [comment]
http://scijs.net/packages/ :)

**Comment by neothemachine** [comment]
Ha! Ok, this has to be linked prominently from the ndarray repo.

**Comment by rreusser** [comment]
Updated the site, so same content except with more packages and searchable by package name:

http://scijs.net/packages

Yeah, should maybe link all the repos to their doc page or something...

**Comment by rreusser** [comment]
Linked at the top. Closing this, although I don't think it'd be a bad idea to link every scijs repo to the scijs doc site.
