### ISSUE TITLE
Docs for transpose are wrong

### ISSUE THREAD

**Issue by rmartinho** [scijs/ndarray#25]
The docs for transpose claim it works in-place, but it does not.

**Comment by mikolalysenko** [comment]
Transpose does not make a copy of the array, it just transposes the view, so it is an O(1) operation.  What would you rather see written here?

**Comment by rreusser** [comment]
Tried to make it slightly clearer: "Finally, for higher dimensional arrays you can transpose the indices without replicating the data. This has the effect of permuting the shape and stride values and placing the result in a new view of the same data. For example, in a 2D array you can calculate the matrix transpose by:"
