### ISSUE TITLE
Convert to JS Array?

### ISSUE THREAD

**Issue by fuzzthink** [scijs/ndarray#36]
How? Tried the suggested ndarray-unpack on a 1D ndarray, didn't work.
thanks.

**Comment by fuzzthink** [comment]
Found out NdArray has tolist() method. However, it's not in the documentation at http://scijs.net/packages/#scijs/ndarray

**Comment by rreusser** [comment]
Can you clarify what didn't work when using `ndarray-unpack`?

**Comment by fuzzthink** [comment]
The thread on issue #29 mentioned ndarray-unpack on "convert an ndarray back to a buffer/array". So I tried
```
nd = require('ndarray')
up = require('ndarray-unpack')
up(nd([1,2]))
```
and errored:
```
TypeError: Cannot read property 'join' of undefined
    at unpackCwise_cwise_thunk (eval at createThunk (/Users/john/dev/testnode/node_modules/cwise-compiler/lib/thunk.js:82:15), <anonymous>:6:49)
    at unpack (/Users/john/dev/testnode/node_modules/ndarray-unpack/unpack.js:19:3)
```

Btw, the tolist() I mentioned turns out to be from numjs, not this ndarray repo.

**Comment by fuzzthink** [comment]
I'm very sorry @rreusser . I called `up` on `ndarray` instead of instance of it. It runs fine. Thank you for your help and I apologies for the time and effort you spent.

**Comment by rreusser** [comment]
@fuzzthink No worries! There are lots of details in using these modules, so lots of subtle things can go wrong when you really get into the details. Glad you got it! Let me/someone know if you encounter other issues.
