### ISSUE TITLE
ndarray modules wiki

### ISSUE THREAD

**Issue by timoxley** [scijs/ndarray#6]
might be a good thing to have the modules listed here available as a wiki page http://0fps.net/2013/06/01/ndarray-modules/

**Comment by rreusser** [comment]
Going to close this due to:

- http://scijs.net/packages/
- https://github.com/scijs/packages/wiki/Packages

the goals of which should be to include all ndarray-compatible modules. If that's not the case, they should be added.

**Comment by timoxley** [comment]
:+1:
